services:
  tagthespot.services.spot.webapi:
    image: ${DOCKER_REGISTRY-}tagthespotservicesspotwebapi
    build:
      context: .
      dockerfile: TagTheSpot.Services.Spot.WebAPI/Dockerfile

  tagthespot.services.spot.database:
    container_name: tagthespot.services.spot.database
    image: postgres:latest
    environment:
      - POSTGRES_DB=tagthespot.services.spot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
