name: Build and deploy ASP.Net Core app to Azure Web App - tagthespot-services-spot

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./src/TagTheSpot.Services.Spot.sln

      - name: Build with dotnet
        run: dotnet build ./src/TagTheSpot.Services.Spot.sln --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./src/TagTheSpot.Services.Spot.WebAPI/TagTheSpot.Services.Spot.WebAPI.csproj \
            -c Release \
            -o ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tagthespot-services-spot'
          slot-name: 'Production'
          package: .

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CE78B44C4390458EB66DE0001BFD2642 }}
